name: lambda-onnx-fastapi-fasthtml-food-classifier
on:
  push:
    branches:
      - main
jobs:
  start-runner:
    name: Start self-hosted EC2 runner for checking test coverage
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.REPO_TOKEN }}
          ec2-image-id: ami-05b9a4f4a4605c80e
          ec2-instance-type: t3.large
          subnet-id: subnet-0fbb0a4e45e210015
          security-group-id: sg-0326e5442e2817762
          # pre-runner-script: |
          #       sudo apt update -y && \
          #       sudo apt-get install -y unzip
          #       curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"  # Download AWS CLI
          #       unzip awscliv2.zip  # Unzip the downloaded file
          #       sudo ./aws/install  # Install AWS CLI
          #       sudo ./aws/install --update
          #       curl -fsSL https://get.docker.com -o get-docker.sh  # Download Docker installation script
          #       sh get-docker.sh  # Run the installation script
          #       # Set up AWS credentials and region
          #       mkdir -p ~/.aws && \
          #       echo "[default]" > ~/.aws/config && \
          #       echo "region=us-east-1" >> ~/.aws/config && \  # Set the region
          #       echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials && \
          #       echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          #       sudo apt-get install nodejs
          #       sudo apt-get install npm
          #       sudo npm install -g aws-cdk
          #       sudo apt install python3.12-venv

  deploy-cdk-lambda:
    name: Deploy cdk
    needs: start-runner
    runs-on: ${{ needs.start-runner.outputs.label }}
    env:
      HOME: /home/runner
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Set AWS Access Key ID
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Set AWS Secret Access Key
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - name: Hello World
        run:  echo 'Hello World! Chirag!'
      - name: Install packages
        run: |
          sudo apt-get update 
          sudo apt-get install unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
      - name: AWS Installation check if aws credentilas are set up correctly or not
        run:  aws s3 ls
      - name: install cdk
        run: |
          sudo apt install nodejs -y
          sudo apt install npm -y
          sudo npm install -g aws-cdk -y
          sudo apt install curl -y
      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh  # Download Docker installation script
          sh get-docker.sh  # Run the installation script
          docker image ls
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install python-venv and activate it and install aws-cdk
        run: |
          sudo apt install python3.12-venv -y
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install constructs
          pip install -r requirements.txt
          python3 --version
          pip list
      - name: deploy cdk
        run:  |
          pip list
          cdk bootstrap
          cdk deploy --require-approval never


  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner # required to get output from the start-runner job
      - deploy-cdk-lambda # required to wait when the main job is done
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.REPO_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}